---
title: "1.3. Triângulo de Pascal. Binómio de Newton."
output: html_document
---

## Triângulo de Pascal

$$\color{red}{^0C_0} \\
\color{red}{^1C_0 \quad ^1C_1} \\
\color{red}{^2C_0 \quad ^2C_1 \quad ^2C_2} \\
\color{red}{^3C_0 \quad ^3C_1 \quad ^3C_2 \quad ^3C_3} \\
\color{red}{^4C_0 \quad ^4C_1 \quad ^4C_2 \quad ^4C_3 \quad ^4C_4} \\$$

$$\color{red}{1} \\
\color{red}{1 \qquad \; 1} \\
\color{red}{1 \qquad \; 2 \qquad \; 1} \\
\color{red}{1 \qquad \; 3 \qquad \; 3 \qquad \; 1} \\
\color{red}{1 \qquad \; 4 \qquad \; 6 \qquad \; 4 \qquad \; 1} \\$$

### Propriedades do Triângulo de Pascal

* Todas as linhas do Triângulo de Pascal começam e acabam em 1

$$^nC_0 = \, ^nC_n$$

* Em qualquer linha do Triângulo de Pascal elementos equidistantes dos extremos são iguais.

$$^nC_p = \, ^nC_{n-p}$$

* A soma de dois elementos consecutivos de uma linha é igual ao número que se situa entre eles na linha seguinte.

$$^nC_p + \, ^nC_{p+1} = \, ^{n+1}C_{p+1} \quad , p \lt n$$

* A soma dos $n + 1$ elementos de qualquer linha do Triângulo de Pascal é igual ao número de subconjuntos de um conjunto com n elementos.

$$\text{Soma dos elementos} = 2^n \Longleftrightarrow \\
\Longleftrightarrow \, ^nC_0 + \, ^nC_1 + \, ^nC_2 + \ldots \, ^nC_{n-2} + \, ^nC_{n-1} + \, ^nC_n = 2^n$$

## Binómio de Newton

Chama-se *desenvolvimento do binómio de Newton* ao desenvolvmento da *n*-ésima potência de $(a+b)$ que é tal que:

$$(a+b)^n = \sum_{k=0}^{n} \, ^nC_k \; a^{n-k} \; b^k \quad ; n \isin \N_0$$

$$(a+b)^n = \, \color{red}{^nC_0} \, a^n + \color{red}{^nC_1} \, a^{n-1} \, b + \color{red}{^nC_2} \, a^{n-2} \, b^2 + \ldots + \color{red}{^nC_{n-2}} \, a^{2} \, b^{n-2} + \color{red}{^nC_{n-1}} \, a \, b^{n-1} + \color{red}{^nC_n} \, b^n$$

Os números $^nC_p$, com $0 \leqslant p \leqslant n$, são designados **coeficientes binomiais**.

No desenvolvimento de $(a+b)^n$, observa-se que:

* há $n+1$ parcelas;
* em cada parcela a soma dos expoentes de $\pmb a$ e de $\pmb b$ é igual a $n$
* os expoentes de $\pmb a$ decrescem de $n$ a $0$ e os de $\pmb b$ crescem de $0$ a $n$

### Termo de ordem $p+1$

No desenvolvimento de $(a+b)^2$, se designarmos o termo de ordem $p+1$ por $T_{p+1}$, com $0 \leqslant p \leqslant n$, tem-se:

$$T_{p+1} = \, ^nC_p \; a^{n-p} \; b^p$$